### ISSUE TITLE
Playtime

### ISSUE THREAD

**Issue by Milkman337** [hulkrelax/hltb-for-deck#1]
Add Playtime for non steam games.

**Comment by hulkrelax** [comment]
Do you have an example where you aren't getting playtime for non steam games because that should already work at least for most games

**Comment by hulkrelax** [comment]
Or are you telling me you want a feature that has nothing to do with how long to beat?

**Comment by Milkman337** [comment]
Yes I mean that on non steam games it tracks how long you have played them as it is definitly needed and it would fit really well in this plugin

**Comment by hulkrelax** [comment]
Closed as personally I think a separate plugin would fit this request better. I understand in theory it kind of makes sense but the scope creep of two very different responsibilities for the plugin I think would make it a mess. I do love the idea of tracking play time for non steam games and if I'm motivated I may try to tackle it in a new plugin.
