### ISSUE TITLE
[FEATURE] Have HLTB data go away after launching game

### ISSUE THREAD

**Issue by CrystalSpore** [hulkrelax/hltb-for-deck#10]
Current behaviour: HLTB data shown during the "Controller Layout" screen

Hopeful end behaviour: Cleaned up output to match closer with the "vanilla" deck experience

Thanks!

**Comment by hulkrelax** [comment]
Hey @CrystalSpore, apologies for never acknowledging this request. I am working on this. It will be in the next update of HLTB For Deck which is likely to be version 1.4.0. 

Thanks for the request!
