### ISSUE TITLE
1.4.0 "Clean" view is horizontal across entire hero

### ISSUE THREAD

**Issue by HirschBerge** [hulkrelax/hltb-for-deck#24]
Instead of the nice, clean and concise stacked view, it is now sprawled across the middle of the hero image like how it is if it is docked to the bottom. Reverting to 1.3.1 fixes this

**Comment by hulkrelax** [comment]
Yep I'm aware. Completely missed it during development. I'm going to put out a fix over the next few days hopefully. For, now I recommend using Clean Default as it doesn't look as jarring and blends with the Steam UI pretty well.

**Comment by HirschBerge** [comment]
Thank you, Hulk!

**Comment by hulkrelax** [comment]
This is fixed in https://github.com/hulkrelax/hltb-for-deck/releases/tag/v1.4.1
