### ISSUE TITLE
Toggle to enable/disable without uninstalling

### ISSUE THREAD

**Issue by joamjoamjoam** [hulkrelax/hltb-for-deck#3]
Is it possible to add a toggle to disable the HLTB section without having to uninstall? It's useful when some themes cause unintended overlap or incompatibilities.

A minimal mode would be pretty cool too

**Comment by hulkrelax** [comment]
Yeah I think that should be possible.

**Comment by joamjoamjoam** [comment]
That would be great. Any thoughts on a minimal mode? I was working a plugin to implement hltb before gett8ng interrupted by work stuff. 

I had something like this in mind along the side of the game view. I could whip something up in a PR if you like the idea 


-------------------------
Main:  12.5       |
Extras: 15         |
Complete: 25.  |
‐----‐-------------------

**Comment by JediRhymeTrix** [comment]
Would it be possible to make the HLTB panel collapsible? Perhaps that would sufficiently reduce the impact on Clean Game View and ProtonDB labels while still allowing the panel to be quickly expanded and be glanced at.

**Comment by hulkrelax** [comment]
See https://github.com/hulkrelax/hltb-for-deck/issues/2#issuecomment-1317429696. I've addressed this with Clean GameView compatible styles for the HLTB for Deck plugin
