### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading'SimpleModal')

### ISSUE THREAD

**Issue by g7755726** [hulkrelax/hltb-for-deck#31]
getting this error upon booting on new steam os update, on the latest stable releases of steam os and decky loader

**Comment by sysmoon14** [comment]
Same here

**Comment by lcorsini** [comment]
same error here:
Latest decky loader
Latest Stable steam client
Latest Stable steam OS

**Comment by BioIron** [comment]
I also have the same issue.
It started about a week ago, with the latest stable steam client update.
Hope it gets fixed sometime.

**Comment by W13N3N** [comment]
I'm also having the same issue

**Comment by bondarev** [comment]
Same

**Comment by Swif2er** [comment]
Just rollback to older version for now as advised here:
https://github.com/hulkrelax/hltb-for-deck/issues/33#issuecomment-1981009223

**Comment by g7755726** [comment]
This has been fixed by the developer so closing my ticket!
