### ISSUE TITLE
Remove UI judder 

### ISSUE THREAD

**Issue by jackgllghr** [hulkrelax/hltb-for-deck#6]
Love the plugin, it would be even better if it didn't cause any UI judder when the "View Details" element is added to the Game Stats component.

A quick fix for this may be to just change the View Details button to a "i" or information icon button, that is absolutely positioned to the right hand side of the container (with position:relative on the overall container) so it doesn't affect the total height of the component when it is shown/hidden

**Comment by jackgllghr** [comment]
Th ask for adding the option to remove the View Details button to 1.2.0, it's a good workaround. I'll try and get my dev environment set up over Xmas and make a PR for the judder fix when it's View Details is shown

**Comment by hulkrelax** [comment]
I think v1.3.0 improves this further as the View Details button is now vertically aligned with all of the stats. I'm going to close this now as complete.
