### ISSUE TITLE
Can't update to 1.2.0 nor do a clean 1.2.0 install

### ISSUE THREAD

**Issue by shigutso** [hulkrelax/hltb-for-deck#7]
My Steam Deck is on the Preview update channel.
Decky version is 2.4.5 Stable channel.
I have the 1.1.1 version installed.
Updating from the Decky settings does not work.
Uninstalling 1.1.1 and trying to install 1.2.0 from the Decky store does not work.
Installing version 1.1.1 again works fine.
There's no error message, just nothing happens.

Are there any log files I can check?

Thanks!

**Comment by atelles** [comment]
I'm having the exact same problem

**Comment by zhzy0077** [comment]
What I saw in logs:
```
Dec 20 14:19:40 steamdeck PluginLoader[11593]: [browser][INFO]: Installing HLTB for Deck (Version: 1.2.0)
Dec 20 14:19:40 steamdeck PluginLoader[11593]: [browser][CRITICAL]: Could not fetch from URL. {
Dec 20 14:19:40 steamdeck PluginLoader[11593]:   "code": "not_found",
Dec 20 14:19:40 steamdeck PluginLoader[11593]:   "message": "File with such name does not exist.",
Dec 20 14:19:40 steamdeck PluginLoader[11593]:   "status": 404
Dec 20 14:19:40 steamdeck PluginLoader[11593]: }
```

**Comment by hulkrelax** [comment]
Going to close this as this is a Decky Plugin Store issue and not specific to this plugin.
